[project]
name = "youtube-downloader"
version = "0.1.0"
description = "YouTube video downloader from scratch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
]
